Fixes for building on 6.7.2 with clang(LLVM=1), required these changes for the following (maybe a couple more) warn/error's.
error: label followed by a declaration is a C23 extension [-Werror,-Wc23-extensions
src/driver/amdxdna/amdxdna_drv.c:189:2: error: variable 'ret' is used uninitialized whenever switch default is taken [-Werror,-Wsometimes-uninitialized]
src/driver/amdxdna/amdxdna_mailbox.c:614:10: error: variable 'mb_chann' is uninitialized when used here [-Werror,-Wuninitialized]
src/driver/amdxdna/amdxdna_mailbox.c:692:2: error: call to undeclared function 'free_irq'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
src/driver/amdxdna/amdxdna_mailbox.c:660:8: error: call to undeclared function 'request_irq'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
src/driver/amdxdna/amdxdna_mailbox.c:376:8: error: unknown type name 'irqreturn_t'
src/driver/amdxdna/amdxdna_mailbox.c:386:9: error: use of undeclared identifier 'IRQ_HANDLED
src/driver/amdxdna/amdxdna_mailbox.c:659:8: error: call to undeclared function 'request_irq'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]